CREATE TABLE ClassLog (
    ID INT PRIMARY KEY NOT NULL IDENTITY(1,1),
    StudentID INT NOT NULL FOREIGN KEY REFERENCES Users(ID),
    ClassID INT NOT NULL FOREIGN KEY REFERENCES Class(ID),
    StudyDate DATE NOT NULL,
    CheckIN TIME,
    CheckOUT TIME,
    HybridSheetID INT NOT NULL FOREIGN KEY REFERENCES HybridSheet(ID),
    TutorID INT NOT NULL FOREIGN KEY REFERENCES Users(ID),
    Progress VARCHAR(16)
)