CREATE TABLE Receipt (
    ID INT PRIMARY KEY NOT NULL IDENTITY(1,1),
    UserID INT NOT NULL FOREIGN KEY REFERENCES Users(ID),
    QuarterID INT NOT NULL FOREIGN KEY REFERENCES Quarter(ID),
    ReceiptFileName VARCHAR(MAX) NOT NULL,
)