CREATE TABLE StudentState(
    ID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
    Grade TINYINT NOT NULL,
    StudentLevel VARCHAR(32),
    Quarter INT NOT NULL FOREIGN KEY REFERENCES Quarter(ID),
    StudentID INT NOT NULL FOREIGN KEY REFERENCES Users(ID),
    Stage VARCHAR(32) NOT NULL,
    Remark VARCHAR(32)
)