CREATE TABLE TutorLogMultiplier(
    ID INT PRIMARY KEY NOT NULL IDENTITY(1,1),
    UserID INT NOT NULL FOREIGN KEY REFERENCES Users(ID),
    TutorLogIntervalID INT NOT NULL FOREIGN KEY REFERENCES TutorLogInterval(ID),
    Multiplier INT NOT NULL
)