CREATE TABLE Chat (
    ID INT PRIMARY KEY NOT NULL IDENTITY(1,1),
    StudentID INT NOT NULL FOREIGN KEY REFERENCES Users(ID),
    ChatTimestamp DATETIME2 NOT NULL DEFAULT(GETDATE()),
    ChatMessage NVARCHAR(MAX) NOT NULL,
    QuarterID INT NOT NULL FOREIGN KEY REFERENCES Quarter(ID),
    SenderID INT NOT NULL FOREIGN KEY REFERENCES Users(ID)
)