CREATE TABLE Comment
(
    ID INT PRIMARY KEY NOT NULL IDENTITY(1,1),
    StudentID INT NOT NULL FOREIGN KEY REFERENCES Users(ID),
    CommentTimestamp DATETIME2 NOT NULL DEFAULT(GETDATE()),
    CommentTextID INT NOT NULL FOREIGN KEY REFERENCES CommentText(ID),
    QuarterID INT NOT NULL FOREIGN KEY REFERENCES Quarter(ID),
    SenderID INT NOT NULL FOREIGN KEY REFERENCES Users(ID),
    Remark VARCHAR(2),
    CommentType VARCHAR(30) NOT NULL
)