module.exports = function (app, db, post, fs, passport, CryptoJS , io) {
	// var auth = require("./auth.js");
	// require("./script/v1/quarter.js")(app, db, post);
	// require("./script/v1/hybrid.js")(app, db, post);
	// require("./script/v1/skill.js")(app, db, post);
	// require("./script/v1/document.js")(app, db, post);
	// require("./script/v1/tutor.js")(app, db, post);
	// require("./script/v1/user.js")(app, db, post, CryptoJS);
	// require("./script/v1/task.js")(app, db, post);
	require("./script/v1/authen.js")(app, db, post, passport);
	// require("./script/v1/video.js")(app, db, post, fs);
	// require("./script/v1/key.js")(app, db, post, fs);
	// require("./script/v1/config.js")(app, db, post, auth);
	// require("./script/v1/qr.js")(app, db, post, fs);
	// require("./script/v1/transaction.js")(app, db, post , io);
	// require("./script/v1/chat.js")(app, db, post);
	// require("./script/v1/quota.js")(app, db, post);
	// require("./script/v1/checkoutLog.js")(app,db,post,io);
	require("./script/v1/notification.js")(app, db, post);
};